version: '2'
services:
  proxy:
    build: .
    restart: always
    ports:
      - "80:80"
    networks:
      - app
    depends_on:
      - web
      - graphql
  web:
    image: ts-react-frontend
    restart: always
    networks:
      app:
        aliases:
          - client
    depends_on:
      - graphql
  graphql:
    image: ts-react
    restart: always
    networks:
      app:
        aliases:
          - graphql
    volumes:
      - ../ts-react:/code

networks:
  app: